baseURL = 'https://inajob.github.io/fbfj/'
relativeURLs = false
canonifyURLs = true
languageCode = 'en-us'
title = "inajob's Picks: Fab Builds from Japan"
theme = 'Blonde'
googleAnalytics = "G-DRJFP4CYLK"

[params]
base_color = "bg-green-600"
description = "inajob shares cool fab builds by Japanese hobbyists and makers — from 3D printing to electronics and more."
paginator_pages = "5"
tagsLimit = 1000
  [params.post]
    # Show thumbnails
    thumbnail = true

    # Disable the "NO IMAGE" image.
    noimage = true

    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "lg:h-44"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "lg:w-auto"

    # Number of characters in description
    description = "130"

  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["social", "tags", "recent"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomies]
tag = "tags"

